import { defaultRegionId } from "./regions.js";

const now = Date.now();

export const sampleComplaints = [
  {
    complaintId: "cmp-road-main-gate",
    userId: "demo-user",
    regionId: defaultRegionId,
    zoneId: "sati-main-gate",
    zoneName: "Main Gate",
    latitude: 23.52305,
    longitude: 77.8158,
    accuracy: 28,
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    description: "Pothole near the main gate causes two wheelers to slow suddenly.",
    aiCategory: "Road Damage",
    aiPriority: "High",
    aiSummary: "A pothole near the main gate is creating a vehicle safety issue.",
    confidence: 0.88,
    tags: ["road", "pothole", "main gate"],
    status: "In Progress",
    supportCount: 18,
    duplicateGroupId: "grp-main-gate-road",
    isDuplicate: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 18).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 35).toISOString(),
    adminNotes: "Civil maintenance team assigned for patching.",
    assignedDepartment: "Civil Maintenance",
    resolutionImageData: "",
    resolvedAt: "",
    anonymous: false,
    timeline: [
      { label: "Reported", at: new Date(now - 1000 * 60 * 60 * 18).toISOString() },
      { label: "Assigned", at: new Date(now - 1000 * 60 * 60 * 8).toISOString() },
      { label: "In Progress", at: new Date(now - 1000 * 60 * 35).toISOString() },
    ],
  },
  {
    complaintId: "cmp-light-hostel",
    userId: "demo-admin",
    regionId: defaultRegionId,
    zoneId: "sati-hostel-zone",
    zoneName: "Hostel Zone",
    latitude: 23.524,
    longitude: 77.8181,
    accuracy: 35,
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    description: "Streetlight beside hostel walkway is not working at night.",
    aiCategory: "Streetlight",
    aiPriority: "Medium",
    aiSummary: "A non-functional hostel walkway light is reducing night visibility.",
    confidence: 0.91,
    tags: ["light", "hostel", "electrical"],
    status: "Open",
    supportCount: 31,
    duplicateGroupId: "grp-hostel-light",
    isDuplicate: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
    adminNotes: "",
    assignedDepartment: "Electrical Department",
    resolutionImageData: "",
    resolvedAt: "",
    anonymous: false,
    timeline: [{ label: "Reported", at: new Date(now - 1000 * 60 * 60 * 7).toISOString() }],
  },
  {
    complaintId: "cmp-drain-workshop",
    userId: "demo-user",
    regionId: defaultRegionId,
    zoneId: "sati-workshop",
    zoneName: "Workshop Area",
    latitude: 23.5213,
    longitude: 77.81602,
    accuracy: 42,
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    description: "Blocked drain near workshop is causing stagnant water and smell.",
    aiCategory: "Blocked Drain",
    aiPriority: "High",
    aiSummary: "A blocked workshop drain is causing stagnant water and sanitation risk.",
    confidence: 0.84,
    tags: ["drain", "water", "sanitation"],
    status: "Triaged",
    supportCount: 12,
    duplicateGroupId: "grp-workshop-drain",
    isDuplicate: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 30).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 60 * 5).toISOString(),
    adminNotes: "Needs sanitation team inspection.",
    assignedDepartment: "Sanitation Team",
    resolutionImageData: "",
    resolvedAt: "",
    anonymous: false,
    timeline: [
      { label: "Reported", at: new Date(now - 1000 * 60 * 60 * 30).toISOString() },
      { label: "Triaged", at: new Date(now - 1000 * 60 * 60 * 5).toISOString() },
    ],
  },
  {
    complaintId: "cmp-library-bench",
    userId: "demo-user-2",
    regionId: defaultRegionId,
    zoneId: "sati-library",
    zoneName: "Central Library",
    latitude: 23.52202,
    longitude: 77.81752,
    accuracy: 21,
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    description: "Broken bench outside library has exposed metal edge.",
    aiCategory: "Broken Furniture",
    aiPriority: "Medium",
    aiSummary: "A damaged library bench has an exposed edge and needs repair.",
    confidence: 0.79,
    tags: ["bench", "library", "safety"],
    status: "Resolved",
    supportCount: 7,
    duplicateGroupId: "grp-library-bench",
    isDuplicate: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 60 * 12).toISOString(),
    adminNotes: "Bench repaired by facility team.",
    assignedDepartment: "Campus Administration",
    resolutionImageData: "",
    resolvedAt: new Date(now - 1000 * 60 * 60 * 12).toISOString(),
    anonymous: false,
    timeline: [
      { label: "Reported", at: new Date(now - 1000 * 60 * 60 * 72).toISOString() },
      { label: "Resolved", at: new Date(now - 1000 * 60 * 60 * 12).toISOString() },
    ],
  },
];

export const sampleVotes = [
  { voteId: "vote-1", complaintId: "cmp-light-hostel", userId: "demo-user", createdAt: new Date(now - 1000 * 60 * 40).toISOString() },
  { voteId: "vote-2", complaintId: "cmp-road-main-gate", userId: "demo-user-2", createdAt: new Date(now - 1000 * 60 * 200).toISOString() },
];
